/**
 * Mock headlines for development/testing when RSS feeds are unavailable
 */

import { RealHeadline } from '@/types/game';

export const MOCK_HEADLINES: RealHeadline[] = [
  {
    id: 'mock_1',
    text: 'Tech Giant Announces New AI Research Center in Seattle',
    source: 'TechCrunch',
    url: 'https://example.com/article1',
    publishedAt: new Date('2024-02-01T00:00:00Z'),
    category: 'tech',
  },
  {
    id: 'mock_2',
    text: 'Global Markets Rally as Economic Data Exceeds Expectations',
    source: 'Reuters',
    url: 'https://example.com/article2',
    publishedAt: new Date('2024-02-02'),
    category: 'business',
  },
  {
    id: 'mock_3',
    text: 'Scientists Discover New Species in Deep Ocean Expedition',
    source: 'BBC News',
    url: 'https://example.com/article3',
    publishedAt: new Date('2024-02-03'),
    category: 'science',
  },
  {
    id: 'mock_4',
    text: 'Renewable Energy Investment Reaches Record High in 2024',
    source: 'Reuters',
    url: 'https://example.com/article4',
    publishedAt: new Date('2024-02-04'),
    category: 'environment',
  },
  {
    id: 'mock_5',
    text: 'Major Sports League Announces Expansion to New Cities',
    source: 'ESPN',
    url: 'https://example.com/article5',
    publishedAt: new Date('2024-02-05'),
    category: 'sports',
  },
  {
    id: 'mock_6',
    text: 'New Study Links Regular Exercise to Improved Mental Health',
    source: 'Health News',
    url: 'https://example.com/article6',
    publishedAt: new Date('2024-02-06'),
    category: 'health',
  },
  {
    id: 'mock_7',
    text: 'Government Unveils Plan to Modernize Infrastructure',
    source: 'Reuters',
    url: 'https://example.com/article7',
    publishedAt: new Date('2024-02-07'),
    category: 'politics',
  },
  {
    id: 'mock_8',
    text: 'Streaming Service Announces Record Subscriber Growth',
    source: 'TechCrunch',
    url: 'https://example.com/article8',
    publishedAt: new Date('2024-02-08'),
    category: 'entertainment',
  },
  {
    id: 'mock_9',
    text: 'Researchers Make Breakthrough in Battery Technology',
    source: 'Science Daily',
    url: 'https://example.com/article9',
    publishedAt: new Date('2024-02-09'),
    category: 'tech',
  },
  {
    id: 'mock_10',
    text: 'International Summit Addresses Climate Change Concerns',
    source: 'BBC News',
    url: 'https://example.com/article10',
    publishedAt: new Date('2024-02-10'),
    category: 'environment',
  },
  {
    id: 'mock_11',
    text: 'Space Agency Confirms Successful Satellite Launch',
    source: 'Space News',
    url: 'https://example.com/article11',
    publishedAt: new Date('2024-02-11'),
    category: 'space',
  },
  {
    id: 'mock_12',
    text: 'Automotive Industry Shifts Focus to Electric Vehicles',
    source: 'Auto News',
    url: 'https://example.com/article12',
    publishedAt: new Date('2024-02-12'),
    category: 'automotive',
  },
  {
    id: 'mock_13',
    text: 'Education Reform Initiative Gains Widespread Support',
    source: 'Education Weekly',
    url: 'https://example.com/article13',
    publishedAt: new Date('2024-02-13'),
    category: 'education',
  },
  {
    id: 'mock_14',
    text: 'Cybersecurity Experts Warn of Emerging Threat Landscape',
    source: 'Security Today',
    url: 'https://example.com/article14',
    publishedAt: new Date('2024-02-14'),
    category: 'tech',
  },
  {
    id: 'mock_15',
    text: 'Tourism Industry Reports Strong Recovery Post-Pandemic',
    source: 'Travel News',
    url: 'https://example.com/article15',
    publishedAt: new Date('2024-02-15'),
    category: 'travel',
  },
];
